uint64 timestamp	# time since system start (microseconds)
uint32 pos_x       # x position
uint32 pos_y       # y position
uint32 pos_z       # z position

uint32 linear_velocity_x       # linear velocity x
uint32 linear_velocity_y       # linear velocity y
uint32 linear_velocity_z       # linear velocity z

uint32 angular_velocity_x       # angular velocity x
uint32 angular_velocity_y       # angular velocity y
uint32 angular_velocity_z       # angular velocity z

char[16] payload_additional_info # Additional informations if needed
